# Generated by Django 2.2.6 on 2020-01-17 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('enquiry_date', models.DateField(auto_now_add=True, null=True)),
                ('emp_code', models.CharField(default='', max_length=2500)),
                ('dpr_no', models.CharField(default='', max_length=2500)),
                ('dpr_month', models.CharField(default='', max_length=2500)),
                ('pros_name', models.CharField(default='', max_length=5000)),
                ('pros_date', models.CharField(default='', max_length=5000)),
                ('pros_month', models.CharField(default='', max_length=5000)),
                ('pros_year', models.CharField(default='', max_length=5000)),
                ('enquiry_by', models.CharField(default='', max_length=5000)),
                ('relation', models.CharField(default='', max_length=5000)),
                ('phone1', models.CharField(default='', max_length=5000)),
                ('phone2', models.CharField(default='', max_length=5000)),
                ('pros_state', models.CharField(default='', max_length=5000)),
                ('pros_city', models.CharField(default='', max_length=5000)),
                ('pros_course', models.CharField(default='', max_length=5000)),
                ('pros_other', models.CharField(default='', max_length=5000)),
                ('pros_interest_states_1', models.CharField(default='', max_length=5000)),
                ('pros_interest_states_2', models.CharField(default='', max_length=5000)),
                ('pros_interest_states_3', models.CharField(default='', max_length=5000)),
                ('pros_10_marks', models.CharField(default='', max_length=5000)),
                ('pros_12_marks', models.CharField(default='', max_length=5000)),
                ('pros_subject_1', models.CharField(default='', max_length=5000)),
                ('pros_subject_2', models.CharField(default='', max_length=5000)),
                ('pros_subject_3', models.CharField(default='', max_length=5000)),
                ('pros_entrance_exam1', models.CharField(default='', max_length=5000)),
                ('pros_entrance_exam2', models.CharField(default='', max_length=5000)),
                ('pros_entrance_exam3', models.CharField(default='', max_length=5000)),
                ('pros_entrance_exam4', models.CharField(default='', max_length=5000)),
                ('pros_budget', models.CharField(default='', max_length=5000)),
                ('pros_register_date', models.CharField(default='', max_length=5000)),
                ('pros_register_month', models.CharField(default='', max_length=5000)),
                ('pros_register_year', models.CharField(default='', max_length=5000)),
                ('pros_register_remarks', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('holiday_id', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_no', models.CharField(default='', max_length=2500)),
                ('holiday_date', models.CharField(default='', max_length=2500)),
                ('holiday_day', models.CharField(default='', max_length=2500)),
                ('holiday_reason', models.CharField(default='', max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_date', models.DateField(auto_now_add=True, null=True)),
                ('notice_no', models.CharField(default='', max_length=2500)),
                ('notice_details', models.CharField(default='', max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Payrolls',
            fields=[
                ('payroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_month', models.CharField(default='', max_length=2500)),
                ('gross_salary', models.CharField(default='', max_length=2500)),
                ('no_of_leaves', models.CharField(default='', max_length=2500)),
                ('loss_of_amount', models.CharField(default='', max_length=2500)),
                ('advance_salary', models.CharField(default='', max_length=2500)),
                ('net_salary', models.CharField(default='', max_length=2500)),
                ('status', models.CharField(default='', max_length=2500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('leaves_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_dated', models.DateTimeField(auto_now_add=True, null=True)),
                ('leave_no_of_days', models.CharField(default='', max_length=2500)),
                ('leave_from_date', models.DateField(blank=True, null=True)),
                ('leave_to_date', models.DateField(blank=True, null=True)),
                ('leave_reason', models.CharField(default='', max_length=2500)),
                ('leave_status', models.CharField(default='Approval Pending', max_length=2500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grievances',
            fields=[
                ('grievance_id', models.AutoField(primary_key=True, serialize=False)),
                ('grievance_dated', models.DateField(auto_now_add=True, null=True)),
                ('grievance_details', models.CharField(default='', max_length=2500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
