# Generated by Django 2.2.6 on 2020-01-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiries',
            name='enquiry_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='grievances',
            name='grievance_dated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='notices',
            name='notice_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
