# Generated by Django 2.2 on 2020-03-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0002_auto_20200117_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiries',
            name='pros_register_status1',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='pros_register_status10',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='pros_register_status2',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='pros_register_status3',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='pros_register_status4',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='pros_register_status5',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='pros_register_status6',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='pros_register_status7',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='pros_register_status8',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='pros_register_status9',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
