# Generated by Django 2.2 on 2020-03-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0003_auto_20200304_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='holiday_city',
            field=models.CharField(default='', max_length=2500),
        ),
    ]
