# Generated by Django 2.2 on 2020-03-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_teammembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Staff.TeamLeaders', unique=True),
        ),
    ]
